[package]
name = "one2html"
version = "0.1.0"
authors = ["Markus Siemens <markus@m-siemens.de>"]
edition = "2018"

[dependencies]
askama = "0.10"
color-eyre = "0.5"
console = "0.13.0"
happylog = { version = "0.1.0", features = ["structopt"] }
indicatif = "0.15.0"
itertools = "0.9.0"
log = "0.4.11"
mime_guess = "2.0.3"
once_cell = "1.4.1"
onenote_parser = "0.2.0"
palette = "0.5.0"
percent-encoding = "2.1.0"
regex = "1"
sanitize-filename = "0.3.0"
structopt = "0.3"

[profile.dev.package.backtrace]
opt-level = 3

[patch.crates-io]
onenote_parser = { path = "/Users/markus/Documents/Coding/OpenSource/onenote.rs" }